### ISSUE TITLE
Error using action

### ISSUE THREAD

**Issue by philiplourandos** [lowply/build-hugo#13]
Busy adding this action to my workflow but I have received this error on 2 versions:

`An action could not be found at the URI 'https://api.github.com/repos/lowply/build-hugo/tarball/0.71.1'`

usage is:

```
jobs:
    build:
        name: Build hugo website
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@master
            - name: build hugo website
              uses: lowply/build-hugo@0.71.1
            - name: Build and push docker image
              uses: mr-smithers-excellent/docker-build-push@v3
              with:
                  image: kbm/website
                  tag: latest
                  registry: docker.pkg.github.com
                  username: ${{ github.actor  }}
                  password: ${{ secrets.BUILD_TOKEN }}
```
